{{- if (include "gsma-open-gateway.capifRequired" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gsma-open-gateway.fullname" . }}-capif
  labels:
    {{- include "gsma-open-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  CAPIF_PASSWORD: {{ .Values.capif.password | b64enc | quote }}
{{- end }}
