{{- if .Values.nefSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gsma-open-gateway.nefSecretName" . }}
  labels:
    {{- include "gsma-open-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.nefSecret.usernameKey }}: {{ required "nefSecret.username is required when nefSecret.create is true" .Values.nefSecret.username | b64enc | quote }}
  {{ .Values.nefSecret.passwordKey }}: {{ required "nefSecret.password is required when nefSecret.create is true" .Values.nefSecret.password | b64enc | quote }}
{{- end }}
