apiVersion: v2
name: gsma-open-gateway
version: 0.2.1
description: Helm chart for deploying the GSMA Open Gateway
type: application
appVersion: "0.1.0"

dependencies:
  - name: redis
    version: "25.3.9"
    repository: "oci://registry-1.docker.io/bitnamicharts"
