# generated by datamodel-codegen:
#   filename:  application-profiles.yaml
#   timestamp: 2026-04-01T11:06:40+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, RootModel, conint, constr


class XCorrelator(RootModel[constr(pattern=r'^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$')]):
    root: constr(pattern=r'^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$') = Field(
        ..., examples=['b4333c46-49c0-4f62-80d7-f0ef930f1c46']
    )


class TimeUnitEnum(Enum):
    Days = 'Days'
    Hours = 'Hours'
    Minutes = 'Minutes'
    Seconds = 'Seconds'
    Milliseconds = 'Milliseconds'
    Microseconds = 'Microseconds'
    Nanoseconds = 'Nanoseconds'


class RateUnitEnum(Enum):
    Bps = 'Bps'
    Kbps = 'Kbps'
    Mbps = 'Mbps'
    Gbps = 'Gbps'
    Tbps = 'Tbps'


class ComputeUnitEnum(Enum):
    Kb = 'Kb'
    Mb = 'Mb'
    Gb = 'Gb'
    Tb = 'Tb'


class PacketErrorLossRate(RootModel[conint(ge=1, le=10)]):
    root: conint(ge=1, le=10) = Field(
        ...,
        description='The exponential power of the allowable error loss rate 10^(-N). For instance 3 would be an error loss rate of 10 to the power of -3 (0.001)\nFor 5G network the 3GPP specification TS 23.203 defines the packet error loss rate QCI attribute. It describes the Quality of Service (QoS) Class Identifier (QCI) parameters used to differentiate traffic classes in mobile networks, ensuring appropriate resource allocation and performance for various services.\nThe packet error loss rate is one of the QCI attributes, providing information on the acceptable packet loss rate for a specific traffic class. This attribute helps maintain the desired performance level for services like voice calls, video streaming, or data transfers within the 3GPP mobile network.',
        examples=[3],
    )


class TargetMinCPU(RootModel[float]):
    root: float = Field(
        ...,
        description='Number of vCPUs required for the application. Fractional values are allowed (e.g., 0.5 = half a vCPU). The value represents the minimum amount of CPU resources to be allocated to the application instance.',
        examples=[0.5],
    )


class TargetMinGPU(RootModel[Any]):
    root: Any = Field(
        ...,
        description='This is the target minimun GPUs required by the application\n',
        examples=[1],
    )


class GpuVendorType(Enum):
    Nvidia = 'Nvidia'
    AMD = 'AMD'


class GpuModelName(RootModel[str]):
    root: str = Field(
        ...,
        description='Model name corresponding to vendorType may include info e.g. for NVIDIA, model name could be “Tesla M60”, “Tesla V100” etc.',
    )


class ErrorInfo(BaseModel):
    status: int = Field(..., description='HTTP response status code')
    code: str = Field(..., description='A human-readable code to describe the error')
    message: str = Field(
        ..., description='A human-readable description of what the event represents'
    )


class Duration(BaseModel):
    value: conint(ge=1) | None = Field(None, examples=[12])
    unit: TimeUnitEnum | None = None


class Rate(BaseModel):
    value: conint(ge=0, le=1024) | None = Field(None, examples=[10])
    unit: RateUnitEnum | None = None


class Compute(BaseModel):
    value: conint(ge=0, le=1024) | None = Field(None, examples=[10])
    unit: ComputeUnitEnum | None = None


class PacketDelayBudget(Duration):
    pass


class Jitter(Duration):
    pass


class TargetMinDownstreamRate(Rate):
    pass


class TargetMinUpstreamRate(Rate):
    pass


class TargetMinMemory(Compute):
    pass


class TargetMinEphemeralStorage(Compute):
    pass


class TargetMinPersistentStorage(Compute):
    pass


class NetworkQualityThresholds(BaseModel):
    packetDelayBudget: PacketDelayBudget | None = None
    targetMinDownstreamRate: TargetMinDownstreamRate | None = None
    targetMinUpstreamRate: TargetMinUpstreamRate | None = None
    packetLossErrorRate: PacketErrorLossRate | None = None
    jitter: Jitter | None = None


class ComputeResourcesThresholds(BaseModel):
    targetMinCPU: TargetMinCPU | None = None
    targetMinMemory: TargetMinMemory | None = None
    gpuVendorType: GpuVendorType | None = None
    gpuModelName: GpuModelName | None = None
    targetMinGPU: TargetMinGPU | None = None
    targetMinGPUMemory: TargetMinMemory | None = None
    targetMinEphemeralStorage: TargetMinEphemeralStorage | None = None
    targetMinPersistentStorage: TargetMinPersistentStorage | None = None


class ApplicationProfile1(BaseModel):
    applicationProfileId: UUID
    networkQualityThresholds: NetworkQualityThresholds
    computeResources: ComputeResourcesThresholds | None = None


class ApplicationProfile2(BaseModel):
    applicationProfileId: UUID
    networkQualityThresholds: NetworkQualityThresholds | None = None
    computeResources: ComputeResourcesThresholds


class ApplicationProfile(RootModel[ApplicationProfile1 | ApplicationProfile2]):
    root: ApplicationProfile1 | ApplicationProfile2


class ApplicationProfileRequest1(BaseModel):
    networkQualityThresholds: NetworkQualityThresholds
    computeResources: ComputeResourcesThresholds | None = None


class ApplicationProfileRequest2(BaseModel):
    networkQualityThresholds: NetworkQualityThresholds | None = None
    computeResources: ComputeResourcesThresholds


class ApplicationProfileRequest(
    RootModel[ApplicationProfileRequest1 | ApplicationProfileRequest2]
):
    root: ApplicationProfileRequest1 | ApplicationProfileRequest2
